version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
     #DATABASE_URL: 'mongodb+srv://mongo_user:mongo_password@cluster0.rvwkt.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
        #depends_on:
        #  - "mongo"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development
# mongo:
#   image: mongo
#   restart: always
#   environment:
#     MONGO_INITDB_ROOT_USERNAME: mongo_user
#     MONGO_INITDB_ROOT_PASSWORD: mongo_password
#   ports:
#     - 27017:27017 # remove this line on prod

#   redis:
#     image: redis
#     ports:
#       - 6379:6379

#   worker:
#     build:
#       context: backend
#       dockerfile: Dockerfile
#     command: celery --app app.tasks worker --loglevel=DEBUG -Q main-queue -c 1

#   flower:
#     image: mher/flower
#     command: flower --broker=redis://redis:6379/0 --port=5555
#     ports:
#         - 5555:5555
#     depends_on:
#       - "redis"

